apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crypto-api
  template:
    metadata:
      labels:
        app: crypto-api
    spec:
      containers:
        - name: crypto-api
          image: crypto-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3001
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          env:
            - name: COIN_API_WS_URL
              value: "wss://ws.coinapi.io/v1/"
            - name: COIN_API_KEY
              value: {KEY}
            - name: REDIS_HOST
              value: "redis-service"
            - name: KAFKA_BROKER
              value: "crypto-alert-kafka.kafka.svc.cluster.local:9092"
            - name: KAFKA_USER
              value: "user"
            - name: KAFKA_PASSWORD
              value: "password"
---
apiVersion: v1
kind: Service
metadata:
  name: crypto-api-service
spec:
  type: ClusterIP
  selector:
    app: crypto-api
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
